# Statically link the MSVC C runtime so nova.exe is self-contained and runs on
# a clean Windows image (no Visual C++ Redistributable required).
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
